### ISSUE TITLE
Missing PDF from link in docs

### ISSUE THREAD

**Issue by pablobaezlinero** [decargroup/navlie#109]
At the beggining of the [imu.py](https://github.com/decargroup/navlie/blob/35b81c61b5946f4cbf11c07fb4f1ccec3e7d467e/navlie/lib/imu.py) file, a link is shown to a PDF describing the detailed derivations. That link is: [https://decargroup.github.io/navlie/_build/html/_static/imu.pdf](https://decargroup.github.io/navlie/_build/html/_static/imu.pdf).

The problem is that it seems not to be working. Can it be fixed so the PDF is available?

Another solution would be to delete the link, but it looks like a good idea to explain the computations.

**Comment by CharlesCossette** [comment]
Thanks for pointing that out! That'll be fixed soon but in the meantime, the PDF is here

https://github.com/decargroup/navlie/blob/main/docs/source/_static/imu.pdf

**Comment by CharlesCossette** [comment]
Link fixed here: https://github.com/decargroup/navlie/pull/110
